apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lucas-maysun-problematic-new 
  description: Secure Supply Chain Example for Audio to Text Application   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=lucas-maysun-problematic-new  
    janus-idp.io/tekton: lucas-maysun-problematic-new 
    backstage.io/kubernetes-id: lucas-maysun-problematic-new 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: rh-ee-lyoon/lucas-maysun-problematic-new
  tags: ["ai", "whispercpp", "python", "asr"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 